/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel_citraluna;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class tambah_page extends javax.swing.JFrame {

    /**
     * Creates new form tambah_page
     */
    private void tambahTamu(String nama_tamu, String alamat_tamu) {
        try (Connection dbconn = Konfig.configDB()) {
            if (dbconn != null) {
                String query = "INSERT INTO tamu (nama_tamu, alamat_tamu) VALUES (?, ?)";
                try (PreparedStatement st = dbconn.prepareStatement(query)) {
                    st.setString(1, nama_tamu);
                    st.setString(2, alamat_tamu);

                    int res = st.executeUpdate();

                    JOptionPane.showMessageDialog(this, "User Data Inserted.", "Successful", JOptionPane.INFORMATION_MESSAGE);

                    // Membersihkan isian kolom setelah operasi pemasukan data
                    txtNamaTamu.setText("");
                    txtAlamatTamu.setText("");

                } catch (SQLException ex) {

                    JOptionPane.showMessageDialog(this, "Failed to Insert User Data.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                System.out.println("The Connection Not Available.");
            }
        } catch (SQLException ex) {

        }
    }

    private void tambahKamar(String nomor_kamar, String tamu_kamar, String harga_kamar) {
        try (Connection dbconn = Konfig.configDB()) {
            if (dbconn != null) {
                String query = "INSERT INTO kamar (nomor_kamar, tamu_kamar, harga_kamar) VALUES (?, ?, ?)";
                try (PreparedStatement st = dbconn.prepareStatement(query)) {
                    st.setString(1, nomor_kamar);
                    st.setString(2, tamu_kamar);
                    st.setString(3, harga_kamar);

                    int res = st.executeUpdate();

                    // Membersihkan isian kolom setelah operasi pemasukan data

                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Failed to Insert User Data.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                System.out.println("The Connection Not Available.");
            }
        } catch (SQLException ex) {
        }
    }

    public tambah_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtNamaTamu = new javax.swing.JTextField();
        txtAlamatTamu = new javax.swing.JTextField();
        txtKamar = new javax.swing.JComboBox<>();
        ccNamaTamu = new javax.swing.JTextField();
        ccTotalPembayaran = new javax.swing.JTextField();
        ccAlamatTamu = new javax.swing.JTextField();
        ccNomorKamar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 51, 255));
        jLabel3.setText("Hotel Citraluna");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HC");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 450, 147, 62));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 540));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        btnTambah.setBackground(new java.awt.Color(255, 255, 255));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/undo-arrow.png"))); // NOI18N
        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(btnTambah)
                .addGap(47, 47, 47)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 620, 90));

        txtNamaTamu.setBackground(new java.awt.Color(204, 204, 204));
        txtNamaTamu.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtNamaTamu.setForeground(new java.awt.Color(204, 51, 255));
        txtNamaTamu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nama Tamu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtNamaTamu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNamaTamuMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtNamaTamuMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtNamaTamuMouseReleased(evt);
            }
        });
        txtNamaTamu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaTamuActionPerformed(evt);
            }
        });
        txtNamaTamu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNamaTamuKeyReleased(evt);
            }
        });
        getContentPane().add(txtNamaTamu, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 270, 60));

        txtAlamatTamu.setBackground(new java.awt.Color(204, 204, 204));
        txtAlamatTamu.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtAlamatTamu.setForeground(new java.awt.Color(255, 51, 255));
        txtAlamatTamu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alamat Tamu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtAlamatTamu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAlamatTamuKeyReleased(evt);
            }
        });
        getContentPane().add(txtAlamatTamu, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 270, 60));

        txtKamar.setBackground(new java.awt.Color(255, 102, 204));
        txtKamar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kamar Standar", "Kamar Deluxe", "Suite Eksekutif", "Karaoke + Pemandu" }));
        txtKamar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 255)));
        txtKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKamarActionPerformed(evt);
            }
        });
        getContentPane().add(txtKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 270, 50));

        ccNamaTamu.setEditable(false);
        ccNamaTamu.setBackground(new java.awt.Color(51, 51, 51));
        ccNamaTamu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ccNamaTamu.setForeground(new java.awt.Color(255, 51, 204));
        ccNamaTamu.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Nama Tamu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(ccNamaTamu, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 220, 60));

        ccTotalPembayaran.setEditable(false);
        ccTotalPembayaran.setBackground(new java.awt.Color(51, 51, 51));
        ccTotalPembayaran.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ccTotalPembayaran.setForeground(new java.awt.Color(255, 51, 204));
        ccTotalPembayaran.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Total Pembayaran", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        ccTotalPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccTotalPembayaranActionPerformed(evt);
            }
        });
        getContentPane().add(ccTotalPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 220, 60));

        ccAlamatTamu.setEditable(false);
        ccAlamatTamu.setBackground(new java.awt.Color(51, 51, 51));
        ccAlamatTamu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ccAlamatTamu.setForeground(new java.awt.Color(255, 51, 204));
        ccAlamatTamu.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Alamat Tamu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(ccAlamatTamu, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 220, 60));

        ccNomorKamar.setEditable(false);
        ccNomorKamar.setBackground(new java.awt.Color(51, 51, 51));
        ccNomorKamar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ccNomorKamar.setForeground(new java.awt.Color(255, 51, 204));
        ccNomorKamar.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Nomor Kamar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(ccNomorKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 220, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background-1.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 620, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        String nama_tamu = txtNamaTamu.getText();
        String alamat_tamu = txtAlamatTamu.getText();
        
        String nomor_kamar = ccNomorKamar.getText();
        String tamu_kamar = ccNamaTamu.getText();
        String harga_kamar = ccTotalPembayaran.getText();

        if (nama_tamu.isEmpty() || alamat_tamu.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Fill up the Form Properly.", "Error", JOptionPane.ERROR_MESSAGE);

        } else {

            //start the login process.
            tambahTamu(nama_tamu, alamat_tamu);
            tambahKamar(nomor_kamar, tamu_kamar, harga_kamar);

        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        txtNamaTamu.setEditable(true);

        txtNamaTamu.setText("");
        txtAlamatTamu.setText("");
        txtKamar.setSelectedItem(1);
        ccNamaTamu.setText("");
        ccAlamatTamu.setText("");
        ccNomorKamar.setText("");
        ccTotalPembayaran.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void ccTotalPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccTotalPembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccTotalPembayaranActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        menu_page mp = new menu_page();
        mp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKamarActionPerformed
        // TODO add your handling code here:

        // Total pembayaran berdasarkan item yang dipilih dari ComboBox
        String selectedKamar = (String) txtKamar.getSelectedItem();
        int hargaKamar = 0;
        String kodeKamar = "";
        switch (selectedKamar) {
            case "Kamar Standar":
                hargaKamar = 600000;
                kodeKamar = "SC";
                break;
            case "Kamar Deluxe":
                hargaKamar = 1200000;
                kodeKamar = "DC";
                break;
            case "Suite Eksekutif":
                hargaKamar = 2000000;
                kodeKamar = "EXC";
                break;
            case "Karaoke + Pemandu":
                hargaKamar = 450000;
                kodeKamar = "KP";
                break;
            // Tambahkan case untuk kamar lainnya sesuai kebutuhan

            default:
                break;
        }

        int nomorKamarRandom = (int) (Math.random() * 90) + 10;
        ccNomorKamar.setText(String.valueOf(kodeKamar + nomorKamarRandom));

        // Hitung total pembayaran
        ccTotalPembayaran.setText(String.valueOf(hargaKamar));
    }//GEN-LAST:event_txtKamarActionPerformed

    private void txtNamaTamuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaTamuActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNamaTamuActionPerformed

    private void txtNamaTamuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNamaTamuMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNamaTamuMouseClicked

    private void txtNamaTamuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNamaTamuMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNamaTamuMouseExited

    private void txtNamaTamuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNamaTamuMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNamaTamuMouseReleased

    private void txtNamaTamuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaTamuKeyReleased
        // TODO add your handling code here:
        String nama_tamu = txtNamaTamu.getText();

        ccNamaTamu.setText(nama_tamu);
    }//GEN-LAST:event_txtNamaTamuKeyReleased

    private void txtAlamatTamuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlamatTamuKeyReleased
        // TODO add your handling code here:
        String alamat_tamu = txtAlamatTamu.getText();
        ccAlamatTamu.setText(alamat_tamu);
    }//GEN-LAST:event_txtAlamatTamuKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambah_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambah_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambah_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambah_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tambah_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTambah;
    private javax.swing.JTextField ccAlamatTamu;
    private javax.swing.JTextField ccNamaTamu;
    private javax.swing.JTextField ccNomorKamar;
    private javax.swing.JTextField ccTotalPembayaran;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtAlamatTamu;
    private javax.swing.JComboBox<String> txtKamar;
    private javax.swing.JTextField txtNamaTamu;
    // End of variables declaration//GEN-END:variables
}
